### ISSUE TITLE
How to use the JpegEncoder class

### ISSUE THREAD

**Issue by peace-shillong** [wizzardo/tools#2]
Hello there, I'm interested in using the Image compression module JpegEncoder, can you kindly guide me through how to run this module.

I don't have IntelliJ IDEA, Is it possible to run the module via command line or Netbeans IDE?
Thank you.

**Comment by wizzardo** [comment]
hello, sorry, didn't see it, all these modules are not runnable, you can only use them from your code.
JpegEncoder has only one public method: Compress(), that will write given image with given quality to specified Stream
